### ISSUE TITLE
Reese code stopped working

### ISSUE THREAD

**Issue by tix9957** [Jackiebibili/ticket_tracker_api#24]
Starting today, I receive the following error:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
    at HTMLIFrameElement.<anonymous> (/**********/js/antibot-simulation.js:4:13038)

Probably something was changed in epsf[.]ticketmaster[.]com/eps-d
Any idea how to fix this?

**Comment by Jackiebibili** [comment]
Hi @tix9957. Thanks for letting me know of the issue. I just checked out the epsf file from ticketmaster and it seems like it has _changed_. Luckily, I have saved an old epsf file on my machine and the old one seems to work just fine. PR https://github.com/Jackiebibili/ticket_tracker_api/pull/25 will be a temporary solution to this issue.
